### ISSUE TITLE
Expose signature format option

### ISSUE THREAD

**Issue by 2fours** [PeculiarVentures/node-webcrypto-ossl#100]
Thanks for this contribution.

In ec_dsa.cpp the signatures are converted to and from DER format (eg. https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/src/ec/ec_dsa.cpp#L134). Any change of exposing a choice here? Other platforms encode the signature in DER, so I've had to fork and expose this myself. Cheers.

**Comment by microshine** [comment]
Signature must be in the same format like browsers have (Chrome, Mozilla, Safari). I think it would be better to make functions like `ConvertDerSignatureToWebCryptoSignature` and `ConvertWebCryptoSignatureToDerSignature ` in your JS project where you use node-webcrypto-ossl. It'll allow you to use the latest version of current module without fork sync.
