### ISSUE TITLE
Strange deriveKey activity

### ISSUE THREAD

**Issue by fuson** [PeculiarVentures/node-webcrypto-ossl#101]
VERY strange:
    let salt = Buffer.from("01020304050607080102030405060708", 'hex');

    let derivedRawKeyArray = await webcrypto.subtle.deriveBits(
        {
            name: "PBKDF2",
            salt: new Uint8Array(salt),
            iterations: 2048,
            hash: {
                name: "SHA-256" //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
            },
        },
        key, //your key from generateKey or importKey
        256
    )

It work ok, but it i'll try call deriveKey with salt without "new Uint8Array(salt))":

    let derivedRawKeyArray = await webcrypto.subtle.deriveBits(
        {
            name: "PBKDF2",
            salt: salt,
            iterations: 2048,
            hash: {
                name: "SHA-256" //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
            },
        },
        key, //your key from generateKey or importKey
        256
    )

derivation will provide random values every call. Is it normal?!?

**Comment by microshine** [comment]
Hello @fuson! Coude you show complited example. I can't repeat your error.

Here is a code I used

```jsavascript
crypto.subtle.importKey("raw", new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0]), { name: "PBKDF2" }, false, ["deriveBits"])
    .then((key) => {
        return crypto.subtle.deriveBits(
            {
                name: "PBKDF2",
                salt: new Uint8Array([1, 2, 3, 4, 5, 6, 7, 8]),
                iterations: 2048,
                hash: {
                    name: "SHA-256" //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
                },
            },
            key, //your key from generateKey or importKey
            256
        )
    })
    .then((derived) => {
        console.log(new Uint8Array(derived))
    })
    .catch((err) => {
        console.error(err);
    })
```

**Comment by fuson** [comment]
Here is full representation code:
node --version v7.8.0
last git codebase

import * as WebCrypto from "node-webcrypto-ossl";

let webcrypto = new WebCrypto();

async function main() {
    const password = "alex";

    const keyBuffer = Buffer.from(password, "utf8");

    let key = await webcrypto.subtle.importKey(
        "raw",
        keyBuffer,
        {
            name: "PBKDF2",
        },
        false,
        ["deriveKey", "deriveBits"]
    );

    const saltBuffer = Buffer.from('0000000000000000', 'hex');

    const derivedKey = await webcrypto.subtle.deriveBits(
        {
            name: "PBKDF2",
            salt: saltBuffer,
            iterations: 2048,
            hash: {
                name: "SHA-256"
            },
        },
        key,
        256
    );

    const derivedKeyBuffer = Buffer.from(derivedKey);


    console.log('key', keyBuffer);
    console.log('salt', saltBuffer);
    console.log('derivedKey', derivedKeyBuffer);
}


main().catch((e) => console.error(e));

**Comment by microshine** [comment]
There is an error with data conversion in module. If I use `Uint8Array` instead of `Buffer`, it works ok.

**Comment by microshine** [comment]
The problem was in `webcrypto-core`. I fixed problem in it. You can update `webcrypto-core` or install the newest version of `node-webcrypto-ossl` v1.0.24

**Comment by fuson** [comment]
Tnx! Спасибо!
