### ISSUE TITLE
Support for AES-CTR

### ISSUE THREAD

**Issue by tarcieri** [PeculiarVentures/node-webcrypto-ossl#104]
I am using AES-CTR in an implementation of AES-SIV:

https://github.com/zcred/sivchain/tree/master/js

AES-CTR with 128-bit and 256-bit keys is supported by Chrome via the WebCrypto API. It is also supported by Firefox (which also supports the 192-bit keys, but I don't care about those personally).

It would be great if this library supported it too.

**Comment by microshine** [comment]
AES-CTR is available in new version 1.0.26

**Comment by tarcieri** [comment]
Fantastic! Thank you!
