### ISSUE TITLE
New Typescript version breaks npm install

### ISSUE THREAD

**Issue by gkaptch1** [PeculiarVentures/node-webcrypto-ossl#107]
Hey,

When trying to install node-webcrypto-ossl today I noticed there was a error from build:e5 tsc.  It looks like a new version of Typescript was released as is being automatically used for building.  Manually downgrading to Typescript@2.3.4 allows for the install to finish without errors.

just running 
`$ npm install node-webcrypto-ossl`
yeilds

>  \> node-webcrypto-ossl@1.0.26 build:es5 /home/gkaptchuk/Repos/temp-test/node_modules/node-webcrypto-ossl  
>
> \> tsc
> 
> lib/crypto/aes.ts(94,13): error TS2322: Type 'Promise<{}>' is not assignable to type 'PromiseLike<ArrayBuffer>'.
>   Types of property 'then' are incompatible.

running 
`$ npm install typescript@2.3.4`
beforehand lets the install complete without errors.

Tested on Ubuntu 16.0.4

Thanks!

**Comment by microshine** [comment]
Thank you for issuer. TS error fixed in v1.0.27

**Comment by gkaptch1** [comment]
Thanks!

**Comment by lightsofapollo** [comment]
Thanks for addressing this so quickly ;)
