### ISSUE TITLE
production use

### ISSUE THREAD

**Issue by anywhichway** [PeculiarVentures/node-webcrypto-ossl#110]
Great package! Seems to be one of the most actively developed crypto packages. Using it because we don't want to provide non-native crypto in the browser and this is the only package we have successfully managed to get to accept WebCrypto generated keys AND generate keys acceptable to WebCrypto. Two questions:

1) Do you have a target time from for endorsing public use?

2) If the above is a long way out, then assistance with this question would be appreciated. We can ALMOST get node crypto to work with WebCrypto for the limited set of options that are common to both and represent a complete, although limited in scope, solution for symmetric, asymmetric encryption and signing. The package we have written [cryptozoa](https://github.com/anywhichway/cryptozoa) will work just in the browser OR just in node but seems to generate incompatible RSA keys. Is it even possible?

**Comment by rmhrisk** [comment]
1. It is probably production ready, we just have not had the time or funds to have a third-party assessment of the code-base. It is being used by several projects in production already. It is up to you to make sure it is suitable for your use though.

2. We dont have the bandwidth o help with this sorry.

**Comment by gmcdev** [comment]
Sorry, adding the following to an issue -- bad git form...but I'm stuck: Am I misunderstanding the usage notes? Thought I could use this in browsers.

I used this library as a stand-in for  `window.crypto.subtle` to run a web-based controller in Node -- worked fine as far as I tested it.

Now I'm trying to use it (back in the browsers) to account for the inconsistent implementations of SubtleCrypto. However, I'm not able to gulp the `.node` binaries.

Any hints or suggestions appreciated~~ Or if I'm barking up the wrong tree, that'd be good to know as well!

**Comment by microshine** [comment]
Try to set `node-webcrypto-ossl` as external module.

Here is example of how I do it on `webpack` for node's `crypto` module in `webcrypto-liner`
https://github.com/PeculiarVentures/webcrypto-liner/blob/master/webpack.config.js#L27
https://github.com/PeculiarVentures/webcrypto-liner/blob/master/src/init.ts#L4-L5

**Comment by gmcdev** [comment]
My hat is off to you Peculiar Gentlemen: This appears to be the missing link I need! I'm a little embarrassed I didn't find it amidst your other Ventures -- so, thank you very much for the lead~~!

I will get the `webcrypto-liner` module implemented & transpiling, and hopefully learn a thing or two from the pro work you guys are doing here. 

-g
