### ISSUE TITLE
digital envelope routines:EVP_DecryptFinal_ex:wrong final block length

### ISSUE THREAD

**Issue by gaspard** [PeculiarVentures/node-webcrypto-ossl#112]
First thanks a lot for this library which helps me test my webcrypto stuff in CI and locally 🙏🏼 !!

Without any change in code, I suddenly get these errors when using subtle.encrypt with AES. 

```
Error: 123145329672192:error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length:../deps/openssl/openssl/crypto/evp/evp_enc.c:520
```

I am passing an ArrayBuffer as data to 'encrypt':

```js
const data = new TextEncoder ().encode ( 'some string to encode' ).buffer
const algo =
{ name: 'AES-CBC'
, length: 128
}
const ivbuf = new Uint8Array ( 16 )
const iv = crypto.getRandomValues ( ivbuf )

subtle.encrypt
( Object.assign ( { iv }, algo )
, key // CryptoKey
, buf
).then ( /* ... */ )
```

**Comment by gaspard** [comment]
This does not happen on the CI server but only on my mac. Both are running node v6.12.2.

**Comment by microshine** [comment]
@gaspard Could you get size of data you are trying to decrypt?
It must be multiple to 16

**Comment by microshine** [comment]
I ran this code on Mac. It works.

I've got the same error if `decrypt` has wrong `enc` size
```js
const WebCrypto = require(".");
const crypto = new WebCrypto();

const data = Buffer.from('some string to encode')
const alg = {
    name: 'AES-CBC',
    length: 128,
}
const iv = crypto.getRandomValues(new Uint8Array(16));

crypto.subtle.generateKey(alg, false, ["encrypt", "decrypt"])
    .then((key) => {
        return crypto.subtle.encrypt(
            Object.assign({ iv }, alg),
            key, // CryptoKey
            data
        )
            .then((enc) => {
                console.log("Enc:", new Buffer(enc).toString("hex"));
                // enc = new Buffer(enc).slice(0, enc.byteLength-1); // reduce enc size by 1
                return crypto.subtle.decrypt(
                    Object.assign({ iv }, alg),
                    key, // CryptoKey
                    enc
                );
            })
            .then((dec) => {
                console.log("Dec:", new Buffer(dec).toString());
            })
    })
    .catch((err) => {
        console.error(err);
    })
```

**Comment by gaspard** [comment]
Wow you are incredible.

My data is a Uint8Array of length 64. I ran your example and it works fine. I will try to see what is wrong...

Thanks a lot for your help. I'll post my error and close this issue when I find what fails.

**Comment by microshine** [comment]
`enc` and `dec` can be `ArrayBuffer`, `Buffer` or `ArrayBufferView`
[index.d.ts](https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/index.d.ts#L6)

**Comment by gaspard** [comment]
The problem is that my encrypted message contains the IV buffer and I use `buffer.subarray ( start, end )` and this fails. If I use `buffer.slice ( start, end )`, it seems to work in node.js.

Is this a bug ? Shouldn't both work ?

Both work on web client.

**Comment by microshine** [comment]
@gaspard I updated test script
I've got error on Mac 
`Error: 123145399431168:error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt:../deps/openssl/openssl/crypto/evp/evp_enc.c:531:`
This code works in Chrome.

It works ok if I change `msg.subarray` to `msg.slice`

```js
const WebCrypto = require("node-webcrypto-ossl");
const crypto = new WebCrypto();

const data = Buffer.from('some string to encode')
const alg = {
    name: 'AES-CBC',
    length: 128,
}
const iv = crypto.getRandomValues(new Uint8Array(16));

function Uint8ArrayConcat(a, b) {
    const res = new Uint8Array(a.byteLength + b.byteLength);
    const v = new Uint8Array(0);
    let index = 0;
    [a, b].forEach((array) => {
        for (let i = 0; i < array.byteLength; i++) {
            res[index++] = array[i]
        }
    });
    return res;
}

crypto.subtle.generateKey(alg, false, ["encrypt", "decrypt"])
    .then((key) => {
        return crypto.subtle.encrypt(
            Object.assign({ iv }, alg),
            key, // CryptoKey
            data
        )
            .then((enc) => {
                const msg = Uint8ArrayConcat(new Uint8Array(enc), iv);
                console.log("Msg:", new Buffer(msg).toString("hex"));
                const enc2 = msg.subarray(0, msg.length - 16);
                console.log("Enc: ", new Buffer(enc).toString("hex"));
                console.log("Enc2:", new Buffer(enc2).toString("hex"));
                console.log("Iv: ", new Buffer(iv).toString("hex"));
                const iv2 = msg.subarray(msg.length - 16);
                console.log("Iv2:", new Buffer(iv2).toString("hex"));
                return crypto.subtle.decrypt(
                    Object.assign({ iv: iv2 }, alg),
                    key, // CryptoKey
                    enc2
                );
            })
            .then((dec) => {
                console.log("Dec:", new Buffer(dec).toString());
            })
    })
    .catch((err) => {
        console.error(err);
    })
```

I'll check it. Thank you

**Comment by microshine** [comment]
Fixed in https://github.com/PeculiarVentures/webcrypto-core/commit/f144508f8fb68d7dd09e7ce16c7230f6da87aacf

**Comment by 786lokesh** [comment]
Hi @microshine , I see the status as a bug level. Is this been fixed ? Because I am also getting the same error. I have not followed your code yet.
Below is my code snippet I am getting this error when I am trying to decrypt the data. I am not sure what's going wrong.
`var decipher = crypto.createDecipher('aes-256-cbc', password);
var decrypted_data = Buffer.concat([decipher.update(decipher_access_token_local), decipher.final()]);
var lToken = JSON.parse(decrypted_data.toString());`

My error message

`Error: error:0606506D:digital envelope routines:EVP_DecryptFinal_ex:wrong final block length
    at Error (native)
    at Decipher.final (crypto.js:158:26)
    at validateAccess (E:\xxx\xxx\server.js:118:94)
    at estimateRef.doc.get.then.doc (E:\xxx\xxx\server.js:190:4)`

Can you tell me where am I going wrong ?

**Comment by microshine** [comment]
@786lokesh Do you use NodeJs `crypto` module?

**Comment by microshine** [comment]
@786lokesh what size of the `decipher_access_token_local ` is? It must be multiple of 16

**Comment by 786lokesh** [comment]
@microshine  yes that is NodeJS crypto module. How can I find out the size of `decipher_access_token_local` ?
