### ISSUE TITLE
Exported types for use with Typescript

### ISSUE THREAD

**Issue by LiraNuna** [PeculiarVentures/node-webcrypto-ossl#113]
How would one use this library as a Typescript module? Specifically, how would typing of results should be handled since as far as I can tell, only the top level `WebCrypto` class is exposed.

```typescript
const WebCrypto = require('node-webcrypto-ossl');
crypto = new WebCrypto();

crypto.subtle.generateKey(...)
    .then(function(key: CryptoKey) {  // <- How should this be typed?
        ...
    });
```

**Comment by microshine** [comment]
@LiraNuna I fixed TS declaration error and published new version of `node-webcrypto-ossl` v1.0.33
Could you try to use new version?

**Comment by microshine** [comment]
It must work like
```ts
import * as WebCrypto from "node-webcrypto-ossl";
const crypto  = new WebCrypto();

 crypto.subtle.generateKey(...)
    .then(...)
```

**Comment by LiraNuna** [comment]
@microshine How does this help in getting the type `CryptoKey`? I'm sorry if I'm missing something

**Comment by microshine** [comment]
@LiraNuna I'm sorry for late answer (just saw your question)

![image](https://user-images.githubusercontent.com/7333669/35053530-5f55b720-fbbb-11e7-8c8a-6ebc61c8a6b7.png)

TypeScript sees `node-webcrypto-ossl` declarations and uses extended WebCrypto interface (KeyStorage)
Standard `lib.dom.d.ts` has Crypto declarations.

Here is example of tsconfig.json for my TS file from image
```json
"compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "lib": [
      "es2015",
      "dom"
    ],
    "strict": true
  }
}
```

**Comment by LiraNuna** [comment]
Yeah that works great!
What I'm talking about is when I need to pass some results around to functions.

For example, imagine I want a function that takes a key and some bytes to perform encryption on.

```typescript
function plzEncrypt(key: ?????, content: Buffer): Buffer {
    // ... impl goes here ... //
}
```

See those question marks? what do I use to type the key? It should be `CryptoKey` but I cannot get the type out of the module in order to type it correctly.

**Comment by microshine** [comment]
There are two ways
1. NodeWebcryptoOpenSSL namespace using
```ts
function Test(key: NodeWebcryptoOpenSSL.CryptoKey) {
}
```

2. Standard TS lib using
You can use `CryptoKey` type from `dom.lib.d.ts`

**Comment by LiraNuna** [comment]
Sorry for my ignorance, but how do you get that namespace?

**Comment by microshine** [comment]
`d.ts` file of `node-webcrypto-ossl` module has declared namespace NodeWebcryptoOpenSSL
https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/index.d.ts#L4

Use `/// <reference types="node-webcrypto-ossl" />`

![image](https://user-images.githubusercontent.com/7333669/35120274-a4b9adec-fca8-11e7-8657-1891889fd01a.png)

**Comment by microshine** [comment]
Another variant

TS shows namespace if you use module in file
![image](https://user-images.githubusercontent.com/7333669/35120336-df2cc180-fca8-11e7-93b5-dcdddf6e26a7.png)

**Comment by LiraNuna** [comment]
Thank you, I wasn't aware that namespaces were implicitly exposed.
