### ISSUE TITLE
ab2b defaults to using an offset of 0, rather than the offset specified in the ArrayBufferView

### ISSUE THREAD

**Issue by aegarbutt** [PeculiarVentures/node-webcrypto-ossl#116]
Thank you for this library!

In trying to determine what was causing a regression in the miscreant/miscreant test suite, I tracked down the changes made to the `ab2b` function between version 1.0.31 and 1.032 to the culprit.

After some debugging, I determined that the issue was that it takes a key provided in a Uint8Array, and then splits into two separate views:

```js
const macKey = keyData.subarray(0, keyData.length / 2 | 0);
const encKey = keyData.subarray(keyData.length / 2 | 0);
```

When passed the `ab2b` function, these values fall through to the second conditonal:

```js
// NOTE: ab.buffer can have another size than view after ArrayBufferView.subarray
return new Buffer(ab.buffer.slice(0, ab.byteLength));
```

Unfortunately, what would happen is that the `macKey` would be used both times and the miscreant tests would fail. This occurred because the both ArrayBufferViews would have the same underlying buffer, but separate byteOffsets.

**Comment by rmhrisk** [comment]
We will fix this
