### ISSUE TITLE
Problem when browserifying

### ISSUE THREAD

**Issue by derpsteb** [PeculiarVentures/node-webcrypto-ossl#118]
Hello to you mighty developers of this promising piece of software and anybody else reading this :D.

I am pretty sure I did miss something but after double checking the documentation and the open and closed issues I could not get the info I needed.

I am looking for a package to do simple RSA encryption within the browser and a node environment. 
For that I installed your package via npm and required it within my code as in https://github.com/PeculiarVentures/node-webcrypto-ossl#using.
After that I tried to browserify the code like this: `browserify index.js -o browser.js`

But this provided me with an error I was not looking for:
```
/path/p2ps/node_modules/node-webcrypto-ossl/build/Release/nodessl.node:1
ELF>�@��@8@���� ����$��$h� ����$��$���$$P�tdpYpYpY�
^
ParseError: Unexpected character ''
```

I also tried building the package from source. Like this:
```
git clone https://github.com/PeculiarVentures/node-webcrypto-ossl.git --depth 1
cd node-webcrypto-ossl
npm install
node-gyp configure
node-gyp build
```
Went fine, but did not change anything.
My node version is 8.9.1. 
I am running Arch Linux if that is of any relevance. 

Hope I can get some input on what I am doing wrong :)

**Comment by rmhrisk** [comment]
`node-webcrypto-ossl` is a native package and will not work in the browser.

We have another project called [webcrypto-liner](https://github.com/PeculiarVentures/webcrypto-liner) that is designed for the browser that is similar in spirit to this.

With that said, depending on your user agent targets you may not need liner now, the most recent browsers do well with most of webcryptos API.

Ryan

**Comment by derpsteb** [comment]
Hello Ryan,

thank you for your quick response. 

So I will have to check if my code is running within a node environment or not and depending on this I will load node-webcrypto-ossl.

Is that correct?

**Comment by rmhrisk** [comment]
Yes. There was a project I saw that added this layer https://www.npmjs.com/package/node-webcrypto-shim but ive never tried it.
