### ISSUE TITLE
dynamic linking error

### ISSUE THREAD

**Issue by wanderer** [PeculiarVentures/node-webcrypto-ossl#120]
Hi. I'm getting this when doing `require(node-webcrypto-ossl)`.

> `node: symbol lookup error: ../node_modules/node-webcrypto-ossl/build/Release/nodessl.node: undefined symbol: OPENSSL_add_all_algorithms_noconf`

The module compiles without any errors. I'm not sure how to debug from here. Let me know if you have any suggestions!

**Comment by microshine** [comment]
@wanderer What version of NodeJS do you use?

**Comment by wanderer** [comment]
@microshine node v9.8.0. Also I should mention this happens only on 9.8.0 so far

**Comment by microshine** [comment]
@wanderer It looks nodejs v9.8.0 uses OpenSSL v1.1.0. Current version of modules is based on OpenSSL v1.0.2

Can you get OpenSSL version from your nodejs?

**Comment by wanderer** [comment]
@microshine i'm not sure how to do this. Any tips?

**Comment by microshine** [comment]
https://stackoverflow.com/questions/6656324/check-for-current-node-version
```
> node
> process.versions
```

**Comment by microshine** [comment]
I created new issue to fix this error https://github.com/PeculiarVentures/node-webcrypto-ossl/issues/121

**Comment by wanderer** [comment]
i have `openssl: '1.1.0g',`

**Comment by microshine** [comment]
@wanderer I installed new version of nodejs v9.8.0. I don't have linking error. Try to rebuild node-webcrypto-ossl module

```
npm rebuild node-webcrypto-ossl
```

**Comment by microshine** [comment]
My nodejs uses OpenSSL v1.0.2n
```
node
> process.version
'v9.8.0'
> process.versions
{ http_parser: '2.7.0',
  node: '9.8.0',
  v8: '6.2.414.46-node.21',
  uv: '1.19.2',
  zlib: '1.2.11',
  ares: '1.13.0',
  modules: '59',
  nghttp2: '1.29.0',
  napi: '2',
  openssl: '1.0.2n',
  icu: '60.2',
  unicode: '10.0',
  cldr: '32.0.1',
  tz: '2017c' }
>
```
