### ISSUE TITLE
Support OpenSSL v1.1.0

### ISSUE THREAD

**Issue by microshine** [PeculiarVentures/node-webcrypto-ossl#121]
NodeJS v9 uses OpenSSL v1.1.0

**Comment by davedoesdev** [comment]
Looks like @alippai has fixed this in https://github.com/tresorit/node-webcrypto-ossl
Any chance of merging those changes in? Node 10 uses OpenSSL v1.1.0 so this module won't install

**Comment by alippai** [comment]
Those changes are incomplete, the EC crypto tests don't pass. As we use this lib for internal testing only, there is little chance we fix all the remaining issues

**Comment by davedoesdev** [comment]
EC crypto tests pass with https://github.com/PeculiarVentures/node-webcrypto-ossl/pull/125
@alippai you had a bug here: https://github.com/tresorit/node-webcrypto-ossl/commit/1b866964af7324ba8485bdb4e487bb439f4e2be2#diff-056e6a9c586f8d59d95060f41164812cR52
(BIGNUMs r and s weren't allocated).
