### ISSUE TITLE
accessing CryptoKey type

### ISSUE THREAD

**Issue by fritzy** [PeculiarVentures/node-webcrypto-ossl#122]
For WebCrypto, I believe that CryptoKey is attached to window -- is it anywhere I can access in this library? I'd like to be able to confirm an `value instanceof CryptoKey`

**Comment by microshine** [comment]
This is good question!

Current version of `node-webcrypto-ossl` exports only Crypto class. So it's impossible to do `value instanceof CryptoKey`

I'll export `CryptoKey` and `SubtleCrypto` from module in new version
