### ISSUE TITLE
Errors building with OpenSSL 1.1.0h

### ISSUE THREAD

**Issue by apowers313** [PeculiarVentures/node-webcrypto-ossl#129]
Using Debian/Buster (testing) with Node.js-8.11.2, npm-1.4.21. [Log here](https://github.com/apowers313/fido2-server-demo/files/2100799/fido2-server-demo.log)

See also apowers313/fido2-server-demo#5

**Comment by microshine** [comment]
NodeJs v8 doesn't support OpenSSL v1.1.0, you need to use OpenSSL v1.0.2 or update NodeJS to v10

https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/src/ec/ec_dsa.cpp#L59

**Comment by yalamber** [comment]
I tried installing this with  both version of OpenSSL v1.0.2 and v1.1.0 my build fails with electron. On node.js it works fine.

**Comment by microshine** [comment]
@yalamber I'm using external OpenSSL library for electron
Use this [.npmrc](https://github.com/PeculiarVentures/fortify/blob/master/.npmrc) file

Use `openssl_1_0_2` option to disable/enable which version of OpenSSL to use. If this option is enabled then OpenSSL must be 1.0.2, otherwise 1.1.0
