### ISSUE TITLE
exportKey : hardcoded key_ops in JWK ?

### ISSUE THREAD

**Issue by jpeisenbarth** [PeculiarVentures/node-webcrypto-ossl#131]
Hello,

`webcrypto.subtle.exportKey(format, AESCryptoKey)` returns a JWK which always contains `key_ops: [ 'encrypt', 'decrypt', 'wrapKey', 'unwrapKey' ]` regardless of the `AESCryptoKey.usages`.

Full (and reproducible) example : 

```
const alg = {
  name: "AES-GCM",
  length: 128
};
webcrypto.subtle.generateKey(alg, true, ["encrypt", "decrypt"]).then(aesCryptoKey => {
    console.log(aesCryptoKey); // usages: [ 'encrypt', 'decrypt' ]
    webcrypto.subtle.exportKey("jwk", aesCryptoKey).then(jwk => {
        console.log(jwk) // key_ops: [ 'encrypt', 'decrypt', 'wrapKey', 'unwrapKey' ]
    })
});
```

In lib/crypto/aes.ts :

```
public static exportKey(format: string, key: CryptoKey): PromiseLike<JsonWebKey | ArrayBuffer> {
        return new Promise((resolve, reject) => {
            const nativeKey = key.native as native.AesKey;
            switch (format.toLocaleLowerCase()) {
                case "jwk":
                    const jwk: JsonWebKey = {
                        kty: "oct",
                        alg: "",
                        key_ops: ["encrypt", "decrypt", "wrapKey", "unwrapKey"], // Hardcoded here
                        k: "",
                        ext: true,
                    };
                    ...
```

I'm wondering if `key_ops: key.usages` instead of `key_ops: ["encrypt", "decrypt", "wrapKey", "unwrapKey"` is not preferable ? 
Especially as webcrypto in the browser is implemented that way (tested with the code above).

If you would like i could create the corresponding PR.

**Comment by microshine** [comment]
PR is appreciated

**Comment by microshine** [comment]
`hmac` uses hard encoded property `key_ops` too
https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/lib/crypto/hmac.ts#L67

**Comment by jpeisenbarth** [comment]
Yup, i will fix it for HMAC also
