### ISSUE TITLE
Build error on Windows with Node 11.9.0

### ISSUE THREAD

**Issue by davedoesdev** [PeculiarVentures/node-webcrypto-ossl#138]
Seeing this on AppVeyor and locally:

```
     Creating library C:\Users\Lucie\centro\node_modules\node-webcrypto-ossl\build\Release\nodessl.lib and object C:\Users\Lucie\centro\node_modules\node-webcrypto-ossl\build\Release\nodessl.exp
ec_jwk.obj : error LNK2001: unresolved external symbol _EC_POINT_get_affine_coordinates_GFp [C:\Users\Lucie\centro\node_modules\node-webcrypto-ossl\build\nodessl.vcxproj]
C:\Users\Lucie\centro\node_modules\node-webcrypto-ossl\build\Release\nodessl.node : fatal error LNK1120: 1 unresolved externals [C:\Users\Lucie\centro\node_modules\node-webcrypto-ossl\build\nodessl.vcxproj]
```

Compiles fine on Linux. This is strange, almost as if the function is missing in the OpenSSL linked with Node 11.9.0 on Windows.

**Comment by rmhrisk** [comment]
Looks like your building against an older OpenSSL

**Comment by davedoesdev** [comment]
The only OpenSSL includes I have on the system are in .node-gyp/... and I have no OpenSSL libraries so it  should be linking against the version in Node itself.

If I use Node 10.15.1 then I don't get the error so I think something's wrong with the OpenSSL in 11.9.0 on Windows.

**Comment by davedoesdev** [comment]
```
C:\Users\David>dumpbin /exports .node-gyp\10.15.1\ia32\node.lib | find "_EC_POINT_get_affine_coordinates_GFp"
                  _EC_POINT_get_affine_coordinates_GFp

C:\Users\David>dumpbin /exports .node-gyp\11.9.0\ia32\node.lib | find "_EC_POINT_get_affine_coordinates_GFp"
```

**Comment by davedoesdev** [comment]
Looks like `EC_POINT_get_affine_coordinates_GFp` has been removed.

**Comment by microshine** [comment]
Try this new module [@peculiar/webcrypto](https://www.npmjs.com/package/@peculiar/webcrypto)
It based on NodeJS Crypto API and doesn't use C++ plugin

**Comment by davedoesdev** [comment]
https://github.com/nodejs/node/issues/25981 and https://github.com/nodejs/node/pull/25991

**Comment by davedoesdev** [comment]
The docs for `EC_POINT_get_affine_coordinates_GFp` [here](https://github.com/openssl/openssl/blob/master/include/openssl/ec.h#L519) says it's a "synonym of
 EC_POINT_set_affine_coordinates" so we should just be able to use that function instead?

**Comment by davedoesdev** [comment]
Fixed in Node 11.10.0 (but this will occur again once the symbols are removed rather than deprecated).

**Comment by lindner** [comment]
Looks like this happened again with Appveyer's 10.16.0 node version..

**Comment by microshine** [comment]
New version `+ node-webcrypto-ossl@1.0.46` is avalable
