### ISSUE TITLE
Issue when traget arch is ia32 while packaging for windows

### ISSUE THREAD

**Issue by yalamber** [PeculiarVentures/node-webcrypto-ossl#139]
Hello, 
I tried to build and it works as my host platform is 64 bit but when I try to build for arch ia32 it results in various openssl errors. Here do I need to change openssl path to 32 bit openssl?

**Comment by microshine** [comment]
Yes, you do. I do it for my Fortify app which uses node-webcrypto-ossl. You can take openssl libs [here](https://github.com/PeculiarVentures/fortify/releases/tag/binaries)

**Comment by yalamber** [comment]
Hello sorry to bother you but I am not sure how to use these prebuilt binaries in my app. Can you give me some hints on this.

**Comment by microshine** [comment]
1. Download x86 version of the OpenSSL and extract it to `C:\OpenSSL\x68`
2. Update your `.npmrc` file
```bash
target_arch = ia32
openssl_dir = C:\OpenSSL\x86
```
3. Install/Rebuild `node-webcrypto-ossl`
