### ISSUE TITLE
LIBEAY32.dll missing when checking nodessl.node in dependency walker for electron app

### ISSUE THREAD

**Issue by yalamber** [PeculiarVentures/node-webcrypto-ossl#140]
Hello, I am using this module with following .npmrc file 
```
runtime = electron
target = 4.0.8
arch = x64
target_arch = x64
disturl = https://atom.io/download/electron
build_from_source = true
openssl_dir = C:\OpenSSL-Win64
openssl_1_0_2 = 1
python = C:\Users\yalamber\Anaconda2\python.exe
msvs_version = 2017
```
Installation works and rebuilds the module as well, Built app also works in the same computer I built but testing that built file in different computer gives error  "The specified module could not be found" Then I searched for the error and I see it happens if some dll are missing in final built file. I checked it with dependency walker and got following error in another computer. here is the screenshot http://prntscr.com/mvu5rl
I think it is also depending on system installed node.exe instead of electron. Is there any way we can fix this.

**Comment by microshine** [comment]
You should put `libeay32,dll` near `electron.exe`

**Comment by yalamber** [comment]
I guess you mean myapp.exe file? I added libeay32.dll in root of the built files. http://prntscr.com/mvv4as I still get same error. I am using electron forge.

**Comment by microshine** [comment]
I'm using `node-webcrypto-ossl` with `electron` in my [Fortify](https://fortifyapp.com/) app

![image](https://user-images.githubusercontent.com/7333669/54085193-10351300-434c-11e9-9938-5a2eda534946.png)

Do you use openssl lib from `C:\OpenSSL-Win64` folder?

**Comment by yalamber** [comment]
yep from C:\Openssl-Win64

**Comment by microshine** [comment]
It can be problem in runtime library. Does your client has C++ runtime library which you use for `node-webcrypto-ossl` compilation?

**Comment by yalamber** [comment]
yes I have installed Visual C++ Redistributable

**Comment by microshine** [comment]
Try [Process Monitor](https://docs.microsoft.com/ru-ru/sysinternals/downloads/procmon)

**Comment by yalamber** [comment]
Are you using latest version of electron for fortify?

**Comment by microshine** [comment]
I'm using Electron v4.0.5. I'm using fortify-prepare to filter file which I need from node_modules (to minimise client app). You don't need to use it

**Comment by microshine** [comment]
Here is the lates version of Fortify
https://github.com/PeculiarVentures/fortify-web/releases/tag/v1.0.18

**Comment by yalamber** [comment]
So I  checked with process minitor and it was indeed issue with libeay32.dll missing and also missing msvcr120.dll, I added msvcr120.dll as well in the app folder and it worked. Thank you so much for pointing me to correct path to figure this out. Also should not that dll files be copied automatically by modules?
