### ISSUE TITLE
Is OpenSSL needed with latest Node?

### ISSUE THREAD

**Issue by innerop** [PeculiarVentures/node-webcrypto-ossl#146]
Hi,

I’ve head the latest version of Node has Upgraded crypto capabilities and no longer requires OpenSSL. For this particular library, do you still need OpenSSL if you were to restrict it to the latest version of Node?

**Comment by microshine** [comment]
Have you seen [@peculiar/webcrypto](https://www.npmjs.com/package/@peculiar/webcrypto)? It uses NodeJS Crypto API and can be run on NodeJS v10 and upper

**Comment by innerop** [comment]
Cool. Thank you.
