### ISSUE TITLE
Support AES_CTR 256

### ISSUE THREAD

**Issue by witchent** [PeculiarVentures/node-webcrypto-ossl#158]
As far as I can see the length for AES_CTR is capped at 128. Could you maybe add support for 256?

**Comment by microshine** [comment]
`node-webcrypto-ossl` has got tests for `AES-CTR`. It supports 128, 192, and 256 keys

![image](https://user-images.githubusercontent.com/7333669/79668905-b181d000-81c0-11ea-97d0-ba49933bc746.png)

See [test logs](https://travis-ci.org/github/PeculiarVentures/node-webcrypto-ossl/jobs/665812471)

**Comment by witchent** [comment]
Thats weird, shouldn't this prevent it?:

```
	LOG_INFO("length");
	if (length < 1 || length > 128) {
		THROW_ERROR("Incorrect value 'length'. Must be between 1 and 128.");
	}
```
(From aes_ctr.cpp)

**Comment by microshine** [comment]
It's 'length' for `encrypt` and `decrypt` params [AesCtrParams](https://www.w3.org/TR/WebCryptoAPI/#aes-ctr-params)

**Comment by witchent** [comment]
Alright that makes sense. Sorry then, I just thought that this would be the case because signal complains about it and needs 256. But this seems to warrant another fork then. Thanks anyway :)

**Comment by microshine** [comment]
### Chrome
![image](https://user-images.githubusercontent.com/7333669/79669509-acbf1b00-81c4-11ea-9ad2-7daa1edcdbe1.png)

**Comment by witchent** [comment]
Yep thats the one I think. Just changing 128 to 256 fixes it but I don't know if this would introduce more problems than help, so feel free to close this issue

**Comment by rmhrisk** [comment]
Not sure I understand. So signal is requiring something that the browser webcrypto does not support (256 bitlength)? And enabling this allows you to build signal desktop on this package?

**Comment by witchent** [comment]
Correct. But as I said in the other issue, while with this check changed to 256 it builds and runs fine, it still does not work (complaining about bad mac, which I actually think has nothing to do with the HMAC but rather with the curve crypto), so it wouldn't really help if you change it anyway.
