### ISSUE TITLE
Should CryptoKeyStorage really be required in v2?

### ISSUE THREAD

**Issue by gnarea** [PeculiarVentures/node-webcrypto-ossl#161]
I'm trying to upgrade from v1 to v2 but the following lines in v2 are problematic because they'll create a directory:

https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/d1fb47d5859336993219fff4443320f91b5ed6f1/lib/crypto.ts#L26-L29
https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/d1fb47d5859336993219fff4443320f91b5ed6f1/lib/key_storage.ts#L23-L27

I'm using this library in a Node.js server where each process should be stateless, so it isn't ideal to have state in the Docker containers. Especially if that state is potentially sensitive.

I'm using this library via PKI.js and I don't have any need to persist data on disk. This worked fine on v1 because the `KeyStorage` was only created if requested:

https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/445714bf8819b5dce11234562c25c147362a98af/lib/webcrypto.ts#L28-L32

I discovered this issue because the upgrade broke the functional tests, since the process shouldn't be allowed to write to the home directory (or any other directory). I can certainly work around that, but before doing that -- are you open to a PR that would only initialise CryptoKeyStorage if a directory is passed to `Crypto`, like in v1 of this library?

**Comment by microshine** [comment]
@gnarea thank you for pointing to this issue. I updated `crypto` and made `keyStorage` optional.

New version `node-webcrypto-ossl@2.0.7` is available

**Comment by gnarea** [comment]
Thank you so much!

**Comment by microshine** [comment]
Have you seen `@peculiar/webcrypto` module? It's alternative of `node-webcrypto-ossl` which is based on NodeJS Crypto API and it doesn't use C++ Addons

**Comment by gnarea** [comment]
I have, but https://github.com/PeculiarVentures/webcrypto/issues/1 is blocking me: The library I wrote to wrap PKI.js/node-webcrypto-ossl is used on the server and will soon be used on an Electron app too.

**Comment by rmhrisk** [comment]
@gnarea its not clear to me how  PeculiarVentures/webcrypto#1 is blocking; it is a discussion thread?

**Comment by microshine** [comment]
@gnarea We've got a project which uses Electron and `@peculiar/webcrypto` works fine there

**Comment by gnarea** [comment]
Apologies, I misread that thread. I thought the upshot of the conversation was that `@peculiar/webcrypto` didn't work in Electron apps. I'll try migrating to `@peculiar/webcrypto` in that case. Thanks!
