### ISSUE TITLE
Error with NODE_MODULE_VERSION 

### ISSUE THREAD

**Issue by IhorKram** [PeculiarVentures/node-webcrypto-ossl#163]
I have an error: 
"
Error: Error occurred while parsing your function triggers.
Error: The module '......./functions/node_modules/apple-pay-signature-and-decrypt/node_modules/node-webcrypto-ossl/build/Release/nodessl.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 79. This version of Node.js requires
NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
"

And "re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`)." - not work
"npm rebuild node-webcrypto-ossl --update-binary" - also not work

**Comment by IhorKram** [comment]
"npm rebuild bcrypt --update-binary"     - also not work

**Comment by microshine** [comment]
Do you have any `.npmrc` options? If it's possible try to use [@peculiar/webcrypto](https://www.npmjs.com/package/@peculiar/webcrypto) module it doesn't use C++ and based on NodeJS Crypto API
