### ISSUE TITLE
`CryptoKey[Symbol.toStringTag]` not implemented.

### ISSUE THREAD

**Issue by septs** [PeculiarVentures/node-webcrypto-ossl#165]

**Comment by brettz9** [comment]
What it turns out our project needs is the following, but added to `webcrypto-core`'s `CryptoKey` (as this is the `CryptoKey` returned by `node-webcrypto-ossl`):

```js
    get [Symbol.toStringTag]() {
        return 'CryptoKey';
    }
```

**Comment by brettz9** [comment]
What it turns out our project needs is the following, but added to `webcrypto-core`'s `CryptoKey` (as this is the `CryptoKey` returned by `node-webcrypto-ossl`):

```js
    get [Symbol.toStringTag]() {
        return 'CryptoKey';
    }
```

Filed https://github.com/PeculiarVentures/webcrypto-core/issues/30 .
