### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by gg3083** [PeculiarVentures/node-webcrypto-ossl#168]
npm ERR! node-webcrypto-ossl@2.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1

**Comment by rmhrisk** [comment]
Without more information, for example logs and what platform you are on, we can’t help much.

It is very likely this is environmental, I recommend switching to peculiar/webcrypto as it has fewer environmental dependencies.

**Comment by gg3083** [comment]
thanks
