### ISSUE TITLE
Node.js 15.x began to provide WebCrypto

### ISSUE THREAD

**Issue by septs** [PeculiarVentures/node-webcrypto-ossl#169]
see https://nodejs.org/api/webcrypto.html

Please record to README file, thanks

**Comment by rmhrisk** [comment]
Cool.

**Comment by rmhrisk** [comment]
Done https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/README.md

**Comment by septs** [comment]
I hope record to
https://github.com/PeculiarVentures/webcrypto-core
https://github.com/PeculiarVentures/webcrypto-liner
thanks

**Comment by rmhrisk** [comment]
Liner has nothing to do with node.
Core is not directly useful to anything but a webcrypto implementation.
