### ISSUE TITLE
ArrayBuffer and Buffer?

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/node-webcrypto-ossl#30]
Right now we support both ArrayBuffer and Buffer. WebCrypto was defined with ArrayBuffer. If developers use Buffer then the code they write will not be interopable. On the other hand node developers commonly use node:buffer and making them switch to array buffer would make library less useful potentially. We need to consider if we want to keep support for both.

**Comment by mitar** [comment]
Please both. :-)

**Comment by l-ko** [comment]
https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/master/lib/subtle.ts#L30

I don't thing it is a good idea. In particular it checks for ArrayBuffer or Uint8Array, and any other data goes to Node buffer.

If you pass Uint16Array then it crashes with:
Assertion failed: (obj->IsUint8Array()), function Data, file ../src/node_buffer.cc, line 188

**Comment by l-ko** [comment]
I think it should also expect data to be the view of ArrayBuffer (ArrayBuffer.isView()) like different typed arrays Uint16Array/Float32Array etc and DataView

**Comment by microshine** [comment]
v1.0.6 support NodeCryptoBuffer = Buffer | ArrayBufferView
