### ISSUE TITLE
Generated keys constructor name

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/node-webcrypto-ossl#31]
generateKey(
            {
                name: 'RSASSA-PKCS1-v1_5',
                modulusLength: 2048, //can be 1024, 2048, or 4096
                publicExponent: new Uint8Array([0x01, 0x00, 0x01]),
                hash: {name: 'SHA-256'}, //can be "SHA-1", "SHA-256", "SHA-384", or "SHA-512"
            },
            true, //whether the key is extractable (i.e. can be used in exportKey)
            ['sign', 'verify'] //can be any combination of "sign" and "verify"
        )

output:
RsaKey {
  usages: [],
  native_: Key { type: 6 },
  extractable: true,
  algorithm: 
   { name: 'RSASSA-PKCS1-v1_5',
     modulusLength: 2048,
     publicExponent: Uint8Array { '0': 1, '1': 0, '2': 1 },
     hash: { name: 'SHA-256' } },
  type: 'private',
  modulusLength: 2048,
  publicExponent: Uint8Array { '0': 1, '1': 0, '2': 1 } }

This leads to a problems of CryptoKey identification. In particular, Jose library fails to identify CryptoKey by 'CryptoKey' constructor name. It further blocks the possibility to use unextractable private keys.

**Comment by microshine** [comment]
Fixed in [RsaKey, AesKey, EcKey -> CryptoKey](https://github.com/PeculiarVentures/node-webcrypto-ossl/commit/344e1f201be7e92a2dcc4824c17728981786b996)
