### ISSUE TITLE
A128CBC-HS256

### ISSUE THREAD

**Issue by l-ko** [PeculiarVentures/node-webcrypto-ossl#35]
This is related to Safari in some way. 

We're using https://github.com/vibornoff/webcrypto-shim WebCrypto polifyll to work in Safari, and it supports AES-CBC, and does not support AES-GCM. Jose lib used for tokens encryption in turn supports A256GCM or A128CBC-HS256 for tokens encryption, which involves wrapping content encryption key.

Since webcrypto-shim does not support AES-GCM, there is only way for Jose with A128CBC-HS256/A256CBC-HS512, which I tested works well.

However server-side node-webcrypto-ossl working well with A256GCM, throws 'Unsupported algorithm' on HMAC raw key import with A128CBC-HS256.

I'm not sure, which is the best way to support Safari in this case.

**Comment by rmhrisk** [comment]
What was the resolution here?

**Comment by l-ko** [comment]
I realized that it is too general stated, may be we should make another more specific issue?

**Comment by rmhrisk** [comment]
I see. Yes,makes sense.
