### ISSUE TITLE
Unclear how to use it as a dependency

### ISSUE THREAD

**Issue by mitar** [PeculiarVentures/node-webcrypto-ossl#46]
Simply listing:

```
"dependencies": {
    "node-webcrypto-ossl": "https://github.com/PeculiarVentures/node-webcrypto-ossl/tarball/9d7a96e62030499379dde14c9a3143776c12a1d2"
}
```

Seems to compile the binary, but `ts` files are not converted to JavaScript, or whatever is needed for

```
var webcrypto = require('node-webcrypto-ossl');
```

then to work from the main code.

**Comment by rmhrisk** [comment]
@mitar is this resolved for y ou?

**Comment by mitar** [comment]
No. I currently have to use my own fork to be able to do it. But I think #50 better represents what has to be done to be able to use it as a dependency.
