### ISSUE TITLE
deriveBits does not seem to be supported

### ISSUE THREAD

**Issue by mitar** [PeculiarVentures/node-webcrypto-ossl#49]
The following code fails:

```javascript
return crypto.subtle.deriveBits({
  name: 'ECDH',
  namedCurve: 'P-256',
  public: peerPublicKey
}, privateKey, 256);
```

I would especially need `deriveBits` for ECDH and above curve.

**Comment by microshine** [comment]
DeriveBits function is not implemented yet.

**Comment by microshine** [comment]
deriveBits for ECDH was added. Current code is not added to NPM yet. Could you test `deriveBits` function with your code befor?

**Comment by mitar** [comment]
Great! I will look into it now.

**Comment by mitar** [comment]
I am getting:

```
Error: Cannot find module './key_storage'
```

**Comment by microshine** [comment]
You should make
```
git pull
tsd install
tsc
npm install
```

**Comment by mitar** [comment]
It does not work. The error I get:

```
Error: Error: 4353290240:error:2B064064:lib(43):ECDH_compute_key:no private value:../deps/openssl/openssl/crypto/ecdh/ech_ossl.c:136:
at SubtleCrypto.deriveBits (node_modules/node-webcrypto-ossl/buildjs/subtle.js:290:16)
```

**Comment by mitar** [comment]
I am working on reproduction.

**Comment by mitar** [comment]
Done: https://github.com/mitar/ecdh-test

```
npm install
node test.js
```

I get:

```
Possible Unhandled Promise Rejection: [Error: 4343992320:error:2B064064:lib(43):ECDH_compute_key:no private value:../deps/openssl/openssl/crypto/ecdh/ech_ossl.c:136:
]
```

**Comment by mitar** [comment]
(Interesting that `]` is in new line.)

**Comment by mitar** [comment]
Also observe that the example works in at least Chrome, if you remove the use of the `Buffer` call at the end.

**Comment by microshine** [comment]
![2016-05-16 20 39 39](https://cloud.githubusercontent.com/assets/7333669/15298116/d3e4fb58-1bae-11e6-9acb-32565db4d369.png)

Is it right?

**Comment by mitar** [comment]
Sorry, I am not sure what you are trying to convey here. :-) So result of `Promise.all` is an array, and it should contain two keys. I just extract them into two variables.

So are you saying that:
* reproduction code has a bug
* that you are confirming that this library has a bug
* or that Chrome is too lenient and that it should not work in Chrome, but it does?

**Comment by microshine** [comment]
It seems I found an error. I chaked `baseKey` from `deriveBits` function. It's not a private key, but it has attr type `private`. It seems export/import EC function has error. I'm checking it.

**Comment by microshine** [comment]
I found an error. I made test with your example, it's ok. Could you test by yourself and close current issue?

**Comment by mitar** [comment]
Hm, now I get:

```
Named corves of EC keys are not equals
```

**Comment by mitar** [comment]
(There is also a typo in `corves`.)

**Comment by mitar** [comment]
Not sure why this does not come up in the reproduction. Maybe because in my case one key comes from browser, and the other key comes from this package.

**Comment by mitar** [comment]
I updated the [reproduction repository](https://github.com/mitar/ecdh-test). It fails with:

```
error [Error: Named corves of EC keys are not equals]
```

Key embedded in the code was generated on Chrome using the same parameters. It seems shorter than what this module generates. Are you sure this module respects parameters for key generation correctly? Because example of the public key for same parameters generated by this module is:

```
3082014b3082010306072a8648ce3d02013081f7020101302c06072a8648ce3d0101022100ffffffff00000001000000000000000000000000ffffffffffffffffffffffff305b0420ffffffff00000001000000000000000000000000fffffffffffffffffffffffc04205ac635d8aa3a93e7b3ebbd55769886bc651d06b0cc53b0f63bce3c3e27d2604b031500c49d360886e704936a6678e1139d26b7819f7e900441046b17d1f2e12c4247f8bce6e563a440f277037d812deb33a0f4a13945d898c2964fe342e2fe1a7f9b8ee7eb4a7c0f9e162bce33576b315ececbb6406837bf51f5022100ffffffff00000000ffffffffffffffffbce6faada7179e84f3b9cac2fc63255102010103420004858c079390e3a9151fdda8536c5a08d336b05092a871d2491a0c56cf27ecbc5fa1c941502921f46e61cf921c94901e7c375d7fab9fb31f995b5a2cf993dd8a59
```

And from Chrome it is:

```
3059301306072a8648ce3d020106082a8648ce3d030107034200047a9f5058422c18043bcb3df3ea56b513a533cfe4c2c3fa489a8606bff6a6677d9a9eb0505fcc8011a329013f96b3646a438ea4e55343a0d3b8fdf60c954c36e5
```

**Comment by microshine** [comment]
Thank you. You found new error. Imported private key doesn't have named curve. 
I have to fix it.

**Comment by microshine** [comment]
I fixed last error (again). I hope it's last error for current issue. I tested code from your repo, it's OK

**Comment by mitar** [comment]
OK, after fixing #52 as well, now it works!

**Comment by mitar** [comment]
It works very well! Thank you! It also improved our crypto speeds a lot!
