### ISSUE TITLE
TypeScript be a local (dev) depencency instead of a global dependency

### ISSUE THREAD

**Issue by Seikho** [PeculiarVentures/node-webcrypto-ossl#58]
`node-gyp` and `mocha` are already consumed correctly in `package.json`, but they rely on an global install (as mentioned in the README).

TypeScript should installed as a dev-depencency and consumed with a `build` script in `package.json`. The compiler changes from version to version and each development environment may have varying versions of the compiler. 

```
// package.json
"scripts": {
  ...
  "build": "tsc"
}
```

Consume with: `npm run build` instead of `tsc`. It adds a little overhead, but it is now deterministic.

**Comment by rmhrisk** [comment]
Pull request welcome

**Comment by rmhrisk** [comment]
We have made npm be pure js so this is not needed
