### ISSUE TITLE
Add coveralls 

### ISSUE THREAD

**Issue by rmhrisk** [PeculiarVentures/node-webcrypto-ossl#68]
https://coveralls.io

**Comment by hildjj** [comment]
I'll take a crack at this.  Proposal:

- use [nyc](https://github.com/istanbuljs/nyc#readme) to generate coverage on travis
- use [coveralls](https://github.com/nickmerwin/node-coveralls#readme) to send the info to coveralls

If you don't mind, I can go a little further for you, and add support for automatically running coverage and refreshing a local [live-server](https://github.com/tapio/live-server#readme) with the HTML coverage report whenever you save a file.

To do this more cleanly for new developers, I propose to add `devDependencies` for 

- typings
- typescript
- mocha
- live-server
- nyc
- [npm-run-all](https://github.com/mysticatea/npm-run-all)

(and only `npm install coveralls` on travis)

I further propose to add several npm script targets to tie the whole thing together.  See [node-cbor](https://github.com/hildjj/node-cbor/blob/master/package.json#L21) for the sorts of things I'm describing, and as a proof that it will work.

**Comment by rmhrisk** [comment]
@hildjj this sounds good to me, we appreciate the help. Sometimes I feel like were boiling the ocean ;)

@microshine this sounds good to me, what do you think? We could take the work that @hildjj does here and use it with node-webcrypto-p11 and the browser-webcrypto-liner project. Any concerns?

**Comment by microshine** [comment]
I like the idea to make project more usable and understandable

**Comment by rmhrisk** [comment]
@hildjj let us know what you need from us. Thanks for the help.

**Comment by hildjj** [comment]
I think all I need from you is for you to create an account at https://coveralls.io/ if you don't have one already, and enable this project.  Travis and coveralls are now automatically integrated.  Tests running for the PR now.

**Comment by rmhrisk** [comment]
Done - https://coveralls.io/github/PeculiarVentures

**Comment by rmhrisk** [comment]
@hildjj Thank you VERY much, I am not sure how long it would have taken us to get to doing this. This will do a lot to help others (and us). Would you be interested/able to apply the same approaches to https://github.com/PeculiarVentures/node-webcrypto-p11/?

**Comment by hildjj** [comment]
I'll take a look at it.
