### ISSUE TITLE
ECDH exportKey with raw format fails

### ISSUE THREAD

**Issue by boldt** [PeculiarVentures/node-webcrypto-ossl#89]
I created this MWE and I am running it with:

* node-webcrypto-ossl 1.0.16
* node 5.8.0

```
var WebCrypto = require("node-webcrypto-ossl");
window = {};
window.crypto = new WebCrypto();

window.crypto.subtle.generateKey(
    {
        name: "ECDH",
        namedCurve: "P-256",
    },
    false,
    ["deriveKey", "deriveBits"]
)
.then(function(key){
    window.crypto.subtle.exportKey(
        "raw",
        key.publicKey
    )
    .then(function(keydata){
        console.log(keydata);
    })
    .catch(function(err){
        console.error(err);
    });

})
.catch(function(err){
    console.error(err);
});
```
It fails with the following error:

```
{ [Error: CryptoKey has 'public' type. It can be used with 'raw' format]
  code: 3,
  message: 'CryptoKey has \'public\' type. It can be used with \'raw\' format' }
```

The error tells me, **It can be used with 'raw' format** - but I can't. If I change raw to jwk, it works.

[The WebCryptoAPI sec sais wrt exportKey](https://www.w3.org/TR/2016/PR-WebCryptoAPI-20161215/#dfn-SubtleCrypto-method-exportKey): *Support of "raw" key formats is encouraged for interoperability.*

It would be nice to get the raw format working, especially for the `exportKey` for ECDH.

**Comment by boldt** [comment]
The corresponding Travis also does not test raw export:

https://travis-ci.org/PeculiarVentures/node-webcrypto-ossl/jobs/196334672#L1265

**Comment by rmhrisk** [comment]
If I understand correctly this is a feature export to support RAW, @boldt we can add this, but would you be able/interested to do a PR for this, I believe it should be straight forward.

**Comment by boldt** [comment]
Yes, I am interested to do a PR, which gives me a change to understand the internals of your library (and WebCrypto) better :)

**Comment by boldt** [comment]
I've started with the raw integration for this package:

https://github.com/boldt/node-webcrypto-ossl/commit/bed62b908092a169556bf6ef04a544c60789f76a

My current status is, that `raw` is the same as `spki` (C&P). Now I'm hanging at this line: 

https://github.com/boldt/node-webcrypto-ossl/blob/raw/src/node/async_ec.cpp#L109

Where the key is exported a spki. I've no clue how to continue to get the `raw` key. I'm looking forward for an advice.

**Comment by microshine** [comment]
I think you can use JWK format. As I can see EC raw format is <04 octet> +<x raw> + <y raw>

**Comment by microshine** [comment]
```javascript
crypto.subtle.generateKey({name: "ECDSA", namedCurve: "P-256"}, false, ["sign"])
.then(function(k){window.keys = k})

crypto.subtle.exportKey("jwk", keys.publicKey).then(function(jwk){console.log(JSON.stringify(jwk))})

crypto.subtle.exportKey("raw", keys.publicKey).then(function(raw){
var res = ""; var buf = new Uint8Array(raw); buf.forEach(function(octet){res += String.fromCharCode(octet)}); console.log(btoa(res))
})
```

Result:
```
{"crv":"P-256","ext":true,"key_ops":[],"kty":"EC","x":"ix-MX9QqGYko8Gz9bGPFTyw0P_EmI1gz7UnKJtMldZw","y":"bZww-vn8I9zKKa3GuGFpMXVvHuG3BbeppyzTwjG4alg"}

BIsfjF/UKhmJKPBs/WxjxU8sND/xJiNYM+1JyibTJXWcbZww+vn8I9zKKa3GuGFpMXVvHuG3BbeppyzTwjG4alg=
```

**Comment by boldt** [comment]
I'm not so sure about it. My current example:

```
window.crypto.subtle.generateKey({ name: "ECDH", namedCurve: "P-256", }, false, ["deriveKey", "deriveBits"])
.then(function(key){

    window.crypto.subtle.exportKey("spki", key.publicKey)
    .then(function(keydata){
        console.log(new Uint8Array(keydata));
    })
    .catch(function(err){
        console.error(err);
    });

    window.crypto.subtle.exportKey("raw", key.publicKey)
    .then(function(keydata){
        console.log(new Uint8Array(keydata));
    })
    .catch(function(err){
        console.error(err);
    });
})
.catch(function(err){
    console.error(err);
});
```

This returns  for spki:

```
[48, 89, 48, 19, 6, 7, 42, 134, 72, 206, 61, 2, 1, 6, 8, 42, 134, 72, 206, 61, 3, 1, 7, 3, 66, 0, 4, 120, 73, 178, 1, 67, 159, 38, 157, 130, 60, 212, 42, 164, 179, 215, 34, 215, 17, 192, 21, 137, 65, 228, 179, 199, 226, 112, 229, 200, 220, 54, 113, 145, 36, 195, 177, 164, 26, 197, 3, 9, 187, 202, 34, 28, 248, 18, 192, 158, 187, 237, 114, 123, 114, 56, 110, 62, 179, 16, 144, 131, 26, 8, 58]
```

and for raw

```
[4, 120, 73, 178, 1, 67, 159, 38, 157, 130, 60, 212, 42, 164, 179, 215, 34, 215, 17, 192, 21, 137, 65, 228, 179, 199, 226, 112, 229, 200, 220, 54, 113, 145, 36, 195, 177, 164, 26, 197, 3, 9, 187, 202, 34, 28, 248, 18, 192, 158, 187, 237, 114, 123, 114, 56, 110, 62, 179, 16, 144, 131, 26, 8, 58]
```

In case of `P-256` (example above) it is always prefixed with (26 byte):

```
[48, 89, 48, 19, 6, 7, 42, 134, 72, 206, 61, 2, 1, 6, 8, 42, 134, 72, 206, 61, 3, 1, 7, 3, 66, 0]
```

A solution could be to take the spki key and remove the prefix. 

Some more research: Looking into [RFC 5480](https://tools.ietf.org/html/rfc5480#section-2), EC SPKI has the following format:

```
  SubjectPublicKeyInfo  ::=  SEQUENCE  {
       algorithm         AlgorithmIdentifier,
       subjectPublicKey  BIT STRING
     }
```

An algorithm identifier (probably my observed prefix) and the public key, following RFC 5480:

```
   The subjectPublicKey from SubjectPublicKeyInfo is the ECC public key.
   ECC public keys have the following syntax:

     ECPoint ::= OCTET STRING
```

So, spki uses the octet string format to store the EC public key. Looking into [this document](http://www.secg.org/sec1-v2.pdf), section *2.3.3 Elliptic-Curve-Point-to-Octet-String Conversion*, it is possible to convert that octet string from a point (e.g., the jwk), which uses polynomial field if not compressed. 

There must be an easier solution to get the public key...

**Comment by microshine** [comment]
Here is decoded values form my example

X: (base64url -> hex)

```
8b1f8c5fd42a198928f06cfd6c63c54f2c343ff126235833ed49ca26d325759c
```

Y: (base64url -> hex)

```
6d9c30faf9fc23dcca29adc6b8616931756f1ee1b705b7a9a72cd3c231b86a58
```

RAW: (base64 -> hex)

```
048B1F8C5FD42A198928F06CFD6C63C54F2C343FF126235833ED49CA26D325759C6D9C30FAF9FC23DCCA29ADC6B8616931756F1EE1B705B7A9A72CD3C231B86A58
```

As you can see to make raw from JWK is easy. I don't like idea to get raw from SPKI, because it can has another value for Named curve block (asn1 `algorithm` has another length). You need to have ASN1 parser to get `subjectPublicKey` and get value from it. I think it is posible but JWK is easy.

You can use `Base64Url` from `webcrypto-core` which allows to convert base64url string to `Uint8Array`
[Base64Url declaration](https://github.com/PeculiarVentures/webcrypto-core/blob/master/index.d.ts#L51)
[Example of usage from node-webcrypto-ossl](https://github.com/PeculiarVentures/node-webcrypto-ossl/blob/cdf9f6cbf1a0499d804a667ddef3528463b3f12c/lib/crypto/rsa.ts#L5)

**Comment by microshine** [comment]
For `importKey` function you can convert raw to JWK. All you have to do is to remove first byte with `04` and split value to get X and Y

**Comment by boldt** [comment]
Based on your explanations, I just created pure JS exportRaw/importRaw functions. They work well. Next step is to get it integrated into this library.

**Comment by microshine** [comment]
@boldt I published new version of `webcrypto-core`. Now you can use exportKey/importKey with `raw` format for EC public keys
https://github.com/PeculiarVentures/webcrypto-core/blob/master/src/ec/crypto.ts#L60-L62.

**Comment by boldt** [comment]
I just pushed a PR. I compiled my code against this PR:

https://github.com/PeculiarVentures/webcrypto-core/pull/4

**Comment by rmhrisk** [comment]
@boldt Thanks!.

Merged so closing

**Comment by boldt** [comment]
Thanks for the quick merge.
